FROM jupyter/minimal-notebook

USER 0

# RUN apt-get update && apt-get install -y openssh-client && \
#    rm -rf /var/lib/apt/lists/*

# install cuda libraries (see https://www.tensorflow.org/install/gpu)
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.1.243-1_amd64.deb && \
    apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub && \
    dpkg -i cuda-repo-ubuntu1804_10.1.243-1_amd64.deb && \
    apt-get update && \
    wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb && \
    apt install ./nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb && \
    apt-get update && \
    apt-get install --no-install-recommends libcudnn7=7.6.5.32+cuda10.1 libcudnn7-dev=7.6.5.32-1+cuda10.1 libnvinfer6=6.0.1-1+cuda10.1 libnvinfer-dev=6.0.1-1+cuda10.1 libnvinfer-plugin6=6.0.1-1+cuda10.1 && \
    rm -rf /var/lib/apt/lists/*

USER 1000

ADD requirements.txt /home/jovyan/.requirements.txt
RUN pip --no-cache-dir install -r /home/jovyan/.requirements.txt

# mlflow creates new conda environment for run (i.e. mlflow run ...) and some dependencies need to be added.
# for example, pysftp is required to access artifact storage.
#
# .condarc is not working with --file flag (i.e. conda env create --file ... see https://github.com/conda/conda/issues/9580)
# there should be other way to add additional dependencies.
#
# as a workaround, adding a pip install command to at the end of activate function in,
#   - /opt/conda/etc/profiles.d/conda.sh
#   - /opt/conda/lib/python3.x/site-packages/conda/shell/etc/profile.d/conda.sh (conda init bash command will rewrite /opt/conda/etc/profiles.d/conda.sh using this)
# while mlflow 'source' this file to run 'conda activate'
# (see https://github.com/mlflow/mlflow/blob/6ef63a7f33ebfe3481ea57cacd94a8a32fc7efd8/mlflow/projects/__init__.py#L493)
RUN find /opt/conda -name conda.sh | xargs sed -i 's/__conda_hashr$/&\n    pip install -q -r \/home\/jovyan\/\.requirements\.txt/'
