apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: jupyter
      context: .
      custom:
        # staroid build env allow executable in /var/run.
        buildCommand: >
          ls -al &&
          sudo mv workspace/repo /var/run/ &&
          cd /var/run/repo &&
          sudo ./build.sh &&
          /var/run/build.sh
deploy:
  kubectl:
    manifests:
      - mlflow-env.yaml
      - k8s.yaml
profiles:
  - name: minikube
    build:
      artifacts:
        - image: jupyter
          context: .
          docker:
            dockerfile: Dockerfile_staroid
    patches:
      - op: add
        path: /deploy/kubectl/manifests/0
        value: minikube.yaml
