apiVersion: skaffold/v2beta1
kind: Config
deploy:
  kubectl:
    manifests:
    - k8s.yaml
profiles:
  - name: minikube
    patches:
      - op: add
        path: /deploy/kubectl/manifests/0
        value: minikube.yaml
